# Generated by Django 5.1.4 on 2025-05-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0007_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
