# Generated by Django 5.1.4 on 2025-05-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0009_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FrameStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=10, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='frameShape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glass.frameshape'),
        ),
        migrations.AddField(
            model_name='product',
            name='frameStyle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glass.framestyle'),
        ),
        migrations.AddField(
            model_name='product',
            name='frameType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glass.frametype'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glass.material'),
        ),
    ]
